data:
  merged_path: "data/raw/data gabungan.xlsx"
  sheets: ["A", "B", "C", "D", "E"]

columns:
  id:
    - NIM
    - Nama
  metadata:
    - Class
    - Scoring_Scheme
    - Assistant_Group

scoring_scheme:
  UNIFIED:
    classes: ['A', 'B', 'C', 'D', 'E']
    weights:
      attendance: 0.10
      tp: 0.15
      response: 0.15
      report: 0.35
      final: 0.25
